name: Build and Push Docker image

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract repo name
        id: repo
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Generate timestamp
        id: timestamp
        run: |
          echo "TIMESTAMP=$(date -u +%Y%m%d-%H%M%S)" >> $GITHUB_ENV
          echo "DATE_TAG=$(date -u +%Y%m%d)" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (cu12)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.cu12
          push: true
          tags: |
            ghcr.io/${{ env.REPO }}:cu12
            ghcr.io/${{ env.REPO }}:cu12-latest
            ghcr.io/${{ env.REPO }}:cu12-${{ env.TIMESTAMP }}
            ghcr.io/${{ env.REPO }}:cu12-${{ env.DATE_TAG }}
            ghcr.io/${{ env.REPO }}:cu12-${{ github.sha }}

      - name: Build and push Docker image (cu12-with-weights)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.cu12.with-weights
          push: true
          tags: |
            ghcr.io/${{ env.REPO }}:cu12-with-weights
            ghcr.io/${{ env.REPO }}:cu12-with-weights-latest
            ghcr.io/${{ env.REPO }}:cu12-with-weights-${{ env.TIMESTAMP }}
            ghcr.io/${{ env.REPO }}:cu12-with-weights-${{ env.DATE_TAG }}
            ghcr.io/${{ env.REPO }}:cu12-with-weights-${{ github.sha }}

      - name: Output image tags
        run: |
          echo "🐳 Published Docker images (cu12):"
          echo "  - ghcr.io/${{ env.REPO }}:cu12"
          echo "  - ghcr.io/${{ env.REPO }}:cu12-latest"
          echo "  - ghcr.io/${{ env.REPO }}:cu12-${{ env.TIMESTAMP }}"
          echo "  - ghcr.io/${{ env.REPO }}:cu12-${{ env.DATE_TAG }}"
          echo "  - ghcr.io/${{ env.REPO }}:cu12-${{ github.sha }}"
          echo "🐳 Published Docker images (cu12-with-weights):"
          echo "  - ghcr.io/${{ env.REPO }}:cu12-with-weights"
          echo "  - ghcr.io/${{ env.REPO }}:cu12-with-weights-latest"
          echo "  - ghcr.io/${{ env.REPO }}:cu12-with-weights-${{ env.TIMESTAMP }}"
          echo "  - ghcr.io/${{ env.REPO }}:cu12-with-weights-${{ env.DATE_TAG }}"
          echo "  - ghcr.io/${{ env.REPO }}:cu12-with-weights-${{ github.sha }}"
